language: minimal
dist: bionic
# install: skip

sudo: false
addons:
  apt:
    update: true
    packages:
     - gnupg
     - python3-pip
     - python3-setuptools

# services: docker
#
# before_install: docker pull ghdl/vunit:llvm

install:
        - $TRAVIS_BUILD_DIR/.travis/download-xilinx.sh
        - pip3 install --user -U fusesoc

script:
# script: docker run --rm -t -v `pwd`:/build -w /build ghdl/vunit:llvm bash -c "apt update && apt install -y python3-pexpect && make GNATMAKE='gnatmake -j'$(nproc) && if [ -n \"$TRAVIS_FULL_CHECK\" ] ; then  make -j$(nproc) check; else make -j$(nproc) check_light ; fi"
        - source $TRAVIS_BUILD_DIR/Xilinx/opt/Xilinx/Vivado/2017.3/settings64.sh
        - fusesoc library add microwatt $TRAVIS_BUILD_DIR/
        - fusesoc run --target=arty_a7-35 microwatt --memory_size=8192 --ram_init_file=$BUILD_DIR/fpga/hello_world.hex


